language: node_js
node_js:
- '6.1'
env:
- NODE_ENV=development CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
notifications:
  slack: cmpt275project:z3kSgdJUNmOKFuQLjbonMWhD
before_install:
- openssl aes-256-cbc -K $encrypted_61a8ed165ccc_key -iv $encrypted_61a8ed165ccc_iv
  -in server/config/secret.js.enc -out server/config/secret.js -d
- openssl aes-256-cbc -K $encrypted_bb3f64d6ea41_key -iv $encrypted_bb3f64d6ea41_iv
  -in server/config/secret.js.enc -out server/config/secret.js -d
